<a href="https://colab.research.google.com/github/tarushsingh09/Word_Vectorization/blob/main/E21CSEU0974_Lab_6_NLP_Tarush_Singh_Word_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Tarush Singh
#E21CSEU0974
#EB-13
#Lab Assignment 06 – Word Vectorization

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
import re
import nltk

# Download NLTK stopwords if not already downloaded
nltk.download('stopwords')

# Load the "20 Newsgroups" dataset
categories = ['sci.med', 'sci.space']
newsgroups_data = fetch_20newsgroups(subset='all', categories=categories, remove=('headers', 'footers', 'quotes'))

# Access the text data
X = newsgroups_data.data

# Preprocessing and cleaning
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Tokenization (split text into words)
    tokens = nltk.word_tokenize(text)
    # Remove stopwords
    tokens = [word for word in tokens if word not in nltk.corpus.stopwords.words('english')]
    # Join tokens back into cleaned text
    cleaned_text = ' '.join(tokens)
    return cleaned_text

# Apply preprocessing to each document
cleaned_documents = [preprocess_text(doc) for doc in X]

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the cleaned documents into a count matrix
count_matrix = vectorizer.fit_transform(cleaned_documents)

# Get the feature names (words) as a list
feature_names = vectorizer.get_feature_names_out()

# Convert the count matrix to an array and create a DataFrame (optional)
import pandas as pd
count_matrix_array = count_matrix.toarray()
count_vectorized_df = pd.DataFrame(count_matrix_array, columns=feature_names)

# Print the cleaned documents, feature names, and the count vectorized data
print("Cleaned Documents:")
for doc in cleaned_documents:
    print(doc)
print("\nFeature Names (Words):", feature_names)
print("\nCount Vectorized Data:")
print(count_vectorized_df)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Cleaned Documents:
cute anecdote hardly indicative population responses ive received post men way get impression unless person willing drop masturbate whenever need desire strikes person hung sex tv programs boobs seinfeld masturbation seinfeld condoms handed high schools teenage pregnancy rate high abortion rate states would assume americans frightened sex rather bit stupid healthy sexuality require flamboyance promiscuity requires responsibility
heard prof mcnally days astronomy undergraduate denouncing photon pollution easy imagine taking practical steps modify sodium lamps street outside mill hill observatory gauge shotgun however seriously possible limit effects streetlights adding reflector light illuminates ground need bonus power consumption required given illumination level reduced strangely enough astronomers often seek lobby elected local authorities use lighting systems considerable success desert areas around major us observatories least thats mcnally told us years ago bri

In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Load the "20 Newsgroups" dataset
newsgroups_data = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))

# Access the target (label) values
y = newsgroups_data.target  # List of category labels

# Create an instance of the OneHotEncoder
encoder = OneHotEncoder(sparse=False)

# Reshape the target labels to a column vector (required by the encoder)
y = np.array(y).reshape(-1, 1)

# Fit and transform the target labels using One-Hot Encoding
y_encoded = encoder.fit_transform(y)

# Print the encoded labels for a few examples
print("Encoded Labels for the First 500 Examples:")
print(y_encoded[:500])


Encoded Labels for the First 500 Examples:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
import re
import nltk

# Download NLTK stopwords if not already downloaded
nltk.download('stopwords')

# Load the "20 Newsgroups" dataset
newsgroups_data = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))

# Access the text data
X = newsgroups_data.data

# Preprocessing and cleaning
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Tokenization (split text into words)
    tokens = nltk.word_tokenize(text)
    # Remove stopwords
    tokens = [word for word in tokens if word not in nltk.corpus.stopwords.words('english')]
    # Join tokens back into cleaned text
    cleaned_text = ' '.join(tokens)
    return cleaned_text

# Apply preprocessing to each document
cleaned_documents = [preprocess_text(doc) for doc in X]

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the cleaned documents into a BoW matrix
bow_matrix = vectorizer.fit_transform(cleaned_documents)

# Get the feature names (words) as a list
feature_names = vectorizer.get_feature_names_out()

# Convert the BoW matrix to an array and create a DataFrame (optional)
import pandas as pd
bow_matrix_array = bow_matrix.toarray()
bow_df = pd.DataFrame(bow_matrix_array, columns=feature_names)

# Print the cleaned documents, feature names, and the BoW matrix
print("Cleaned Documents:")
for doc in cleaned_documents:
    print(doc)
print("\nFeature Names (Words):", feature_names)
print("\nBag of Words Matrix:")
print(bow_df)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Cleaned Documents:
sure bashers pens fans pretty confused lack kind posts recent pens massacre devils actually bit puzzled bit relieved however going put end nonpittsburghers relief bit praise pens man killing devils worse thought jagr showed much better regular season stats also lot fo fun watch playoffs bowman let jagr lot fun next couple games since pens going beat pulp jersey anyway disappointed see islanders lose final regular season game pens rule
brother market highperformance video card supports vesa local bus mb ram anyone suggestionsideas diamond stealth pro local bus orchid farenheit ati graphics ultra pro highperformance vlb card please post email thank matt
finally said dream mediterranean new area greater years like holocaust numbers ist july usa sweden april still cold changed calendar nothing mentioned true let say true shall azeri women children going pay price raped killed tortured armenians hearded something called geneva convention facist ohhh forgot armenians fight

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



mark dont specify means government prevented becoming tool business interests leftwing big government conventional liberal im willing vote anticompetitive regulations favor auto dealers hear libertarians desire limit incumbents terms weaken government eliminating power enforce antitrust laws desire eliminate legislators pay strikes particularly ineffective way insure auto dealers special interests influence public policy fact seem clearly designed accomplish opposite jsh
dean velasco quoted letter james stowell president moody bible institute lot discussion far nobody seems hit exactly criticism arrogance aimed arrogance attacked think ones know absolutes short many evangelicals claim infallible matter religious texts particular problem one epistemology shorthand think epistemology know question turns troubling one problem absolute certainty bottom least thinking goes inside head unless certain everything happens head infallible reasoning discover source truth question means absolute j

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



       aa  aaa  aaaaa  aaaaaaaaaaaa  \
0       0    0      0             0   
1       0    0      0             0   
2       0    0      0             0   
3       0    0      0             0   
4       0    0      0             0   
...    ..  ...    ...           ...   
18841   0    0      0             0   
18842   0    0      0             0   
18843   0    0      0             0   
18844   0    0      0             0   
18845   0    0      0             0   

       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaauuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuugggggggggggggggg  \
0                                                      0                                 
1                                                      0                                 
2                                                      0                                 
3                                                      0                                 
4                                                      0                         